### ISSUE TITLE
case sensitive fuzzy filters

### ISSUE THREAD

**Issue by jandamm** [machakann/asyncomplete-ezfilter.vim#1]
Hi I'm playing around with the filters and I'm wondering if it's possible to use jw or osa filters but still searching case sensitive?

**Comment by machakann** [comment]
Unfortunately, it is not available at this moment. Do you want it?

**Comment by jandamm** [comment]
I'm not sure yet.
My first intuition was that I'd use it.
But after second thought I'm not so sure.

I'm primarily writing in Swift where you use camel case and Types start with a capital letter, functions and variables with a small letter.
So my thought was that it'd be helpful.
But I'd probably only want the first letter to be case sensitive. But this would be confusing as well.

**Comment by machakann** [comment]
I added an option for each matching methods. You can try case-sensitive fuzzy-matching for example:

```vim
let s:FALSE = 0
let g:asyncomplete#preprocessor#ezfilter#config['*'] =
  \ {ctx, items -> ctx.osa_filter(items, 2, s:FALSE)}
```

The case-sensitive matching only for the first character is somehow tricky. Thus, it would not be supported officially but it is not so difficult.

```vim
let g:asyncomplete#preprocessor#ezfilter#config['*'] =
\ {ctx, items -> s:myfilter(ctx, items, 2)}

function! s:myfilter(ctx, items, thr) abort
  let base = a:ctx.base
  if base ==# ''
    return a:items
  endif
  let c = base[0]
  let items = filter(copy(a:items), 'v:val.word[0] ==# c')
  return a:ctx.osa_filter(items, a:thr)
endfunction
```

**Comment by jandamm** [comment]
Thank you!
I'll have a look how it feels :)
