### ISSUE TITLE
Error with latest asyncomplete-omni

### ISSUE THREAD

**Issue by jsit** [machakann/asyncomplete-ezfilter.vim#3]
When using `jw_filter` with [yami-beta/asyncomplete-omni.vim](https://github.com/yami-beta/asyncomplete-omni.vim), I get this error:

```
Error detected while processing function <SNR>183_recompute_pum[43]..asyncomplete#preprocessor#ezfilter#filter[7]..<lambda>5[1]..<lambda>27[1]..<SNR>229_jw_filter:
line    3:
Traceback (most recent call last):
```

It may be an error with the way asyncomplete-omni works, so I'm filing an issue there too: yami-beta/asyncomplete-omni.vim#21

**Comment by machakann** [comment]
What kind of language did you write when you saw the error?

**Comment by jsit** [comment]
Looks like this was my mistake, sorry for the false alarm. Can't reproduce, closing.
